Data/Docs: https://www.kaggle.com/datasets/wyattowalsh/basketball?resource=download

#### This notebook consists of SQL queries of NBA data. The results of these queries could be interesting information to bring up during a broadcast.

In [1]:
from dotenv import load_dotenv
import os

from sqlalchemy import create_engine, text, literal
import pandas as pd

In [2]:
load_dotenv()
password = os.getenv("DB_PASSWORD")

In [3]:
engine = create_engine(
    f"postgresql://postgres:{password}@localhost:5432/nba_data"
)

### Reading in all the data (excluding play_by_play and team_info_common datasets)

In [4]:
df_player_info = pd.read_csv("common_player_info.csv")
df_draft_stats = pd.read_csv("draft_combine_stats.csv")
df_draft_history = pd.read_csv("draft_history.csv")
df_game = pd.read_csv("game.csv")
df_game_info = pd.read_csv("game_info.csv")
df_game_summary = pd.read_csv("game_summary.csv")
df_inactive = pd.read_csv("inactive_players.csv")
df_line_score = pd.read_csv("line_score.csv")
df_officials = pd.read_csv("officials.csv")
df_other = pd.read_csv("other_stats.csv")
# df_play_by_play = pd.read_csv("play_by_play.csv")
df_player = pd.read_csv("player.csv")
df_team = pd.read_csv("team.csv")
df_team_details = pd.read_csv("team_details.csv")
df_team_history = pd.read_csv("team_history.csv")
# df_team_info_common = pd.read_csv("team_info_common.csv")

In [5]:
df_player_info.to_sql(
    "player_info",
    engine,
    if_exists="replace",
    index=False
)

df_draft_stats.to_sql(
    "draft_stats",
    engine,
    if_exists="replace",
    index=False
)

df_draft_history.to_sql(
    "draft_history",
    engine,
    if_exists="replace",
    index=False
)

df_game.to_sql(
    "game",
    engine,
    if_exists="replace",
    index=False
)

df_game_info.to_sql(
    "game_info",
    engine,
    if_exists="replace",
    index=False
)

df_game_summary.to_sql(
    "game_summary",
    engine,
    if_exists="replace",
    index=False
)

df_inactive.to_sql(
    "inactive",
    engine,
    if_exists="replace",
    index=False
)

df_line_score.to_sql(
    "line_score",
    engine,
    if_exists="replace",
    index=False
)

df_officials.to_sql(
    "officials",
    engine,
    if_exists="replace",
    index=False
)

df_other.to_sql(
    "other",
    engine,
    if_exists="replace",
    index=False
)

df_player.to_sql(
    "player",
    engine,
    if_exists="replace",
    index=False
)

df_team.to_sql(
    "team",
    engine,
    if_exists="replace",
    index=False
)

df_team_details.to_sql(
    "team_details",
    engine,
    if_exists="replace",
    index=False
)

df_team_history.to_sql(
    "team_history",
    engine,
    if_exists="replace",
    index=False
)

# Not included:

# df_play_by_play.to_sql(
#     "play_by_play",
#     engine,
#     if_exists="replace",
#     index=False
# )

# df_team_info_common.to_sql(
#     "team_info_common",
#     engine,
#     if_exists="replace",
#     index=False
# )

52

# Querying

#### 1: Avg home attendance for teams

In [26]:
query = text("""Select team_name_home, avg(attendance) as avg_attendance
FROM game_info i NATURAL JOIN game g 
GROUP BY team_name_home
ORDER BY avg_attendance DESC
;""")

pd.read_sql(query,engine)

                     team_name_home  avg_attendance
0                   Detroit Falcons             NaN
1           Roma Virtus Lottomatica             NaN
2           Providence Steamrollers             NaN
3                Pittsburgh Ironmen             NaN
4    Lyon-Villeurbanne Adecco ASVEL             NaN
..                              ...             ...
93                St. Louis Bombers          2206.0
94                    Chicago Stags          2071.5
95    Unicaja Malaga Unicaja Malaga             0.0
96     Lottomatica Lottomatica Roma             0.0
97  MMT Estudiantes MMT Estudiantes             0.0

[98 rows x 2 columns]

#### 2: Number of games played each year

In [27]:
query = text("""SELECT SUBSTRING(split_part(game_date, ' ', 1) FROM '^([0-9]+)') AS year, count(*) AS num_games
FROM game_info g
GROUP BY year
ORDER BY year
;""")

pd.read_sql(query,engine)

    year  num_games
0   1946        103
1   1947        237
2   1948        244
3   1949        404
4   1950        426
..   ...        ...
73  2019       1162
74  2020        677
75  2021       1555
76  2022       1271
77  2023        695

[78 rows x 2 columns]

#### 3: Count of players in each weight group 180-189, 190-199, 200-209, etc.

In [30]:
query = text("""select 
	FLOOR(weight/10)*10 AS weight_group_start,
	FLOOR(weight/10)*10 + 9 as weight_group_end,
	Count(*) as num_players
from player_info
group by floor(weight/10)
ORDER BY weight_group_start;""")
pd.read_sql(query, engine)

    weight_group_start  weight_group_end  num_players
0                130.0             139.0            3
1                140.0             149.0            2
2                150.0             159.0           13
3                160.0             169.0           81
4                170.0             179.0          288
5                180.0             189.0          497
6                190.0             199.0          551
7                200.0             209.0          508
8                210.0             219.0          598
9                220.0             229.0          502
10               230.0             239.0          340
11               240.0             249.0          291
12               250.0             259.0          189
13               260.0             269.0          102
14               270.0             279.0           58
15               280.0             289.0           23
16               290.0             299.0           12
17               300.0             309.0            6
18               310.0             319.0            3
19               320.0             329.0            2
20               330.0             339.0            1
21               360.0             369.0            1
22                 NaN               NaN          100

#### 4: Count of players based on jersey number group 0-9, 10-19, 20-29, etc.

In [7]:
#First, making a new table of the form person_id, first_name, last_name, jersey
query = text('CREATE TABLE jersey_info AS SELECT person_id, first_name, last_name, jersey FROM player_info')

with engine.begin() as conn:
    conn.execute(query)

In [9]:
#Next, adding jersey_changed and current_jersey
query = text('ALTER TABLE jersey_info ADD current_jersey INT;')
query2 = text('ALTER TABLE jersey_info ADD jersey_changed BOOLEAN DEFAULT FALSE;')

with engine.begin() as conn:
    conn.execute(query)
    conn.execute(query2)

In [13]:
#Updating current_jersey
query = text("UPDATE jersey_info SET current_jersey = substring(jersey FROM '([0-9]+)$')::INT;")

with engine.begin() as conn:
    conn.execute(query)

In [14]:
#Updating jersey_changed
query = text("UPDATE jersey_info SET jersey_changed = jersey LIKE '%-%';")

with engine.begin() as conn:
    conn.execute(query)

In [31]:
#Finally, the query
query = text("""select 
	FLOOR(current_jersey/10)*10 AS jersey_group_start,
	FLOOR(current_jersey/10)*10 + 9 as jersey_group_end,
	Count(*) as num_players
from jersey_info
group by floor(current_jersey/10)
ORDER BY jersey_group_start;""")

pd.read_sql(query, engine)

    jersey_group_start  jersey_group_end  num_players
0                  0.0               9.0          829
1                 10.0              19.0          785
2                 20.0              29.0          592
3                 30.0              39.0          447
4                 40.0              49.0          318
5                 50.0              59.0          187
6                 60.0              69.0            4
7                 70.0              79.0           10
8                 80.0              89.0            6
9                 90.0              99.0           13
10                 NaN               NaN          980

#### 5.1: Percent of home games won by all players

In [12]:
query = text("""SELECT first_name, last_name, team_name,
ROUND(AVG(CASE WHEN wl_home = 'W' THEN 1.0 ELSE 0.0 END)*100, 2) AS percent_home_games_won,
SUM(CASE WHEN wl_home = 'W' THEN 1 ELSE 0 END) AS num_home_games_won,
count(*) AS num_home_games_played
FROM 
	(select g.team_id_home, p.team_name, game_id, p.first_name, p.last_name, g.wl_home 
	from game g join player_info p ON p.team_id = g.team_id_home)
GROUP BY first_name, last_name, team_name
ORDER BY percent_home_games_won DESC
;""")

pd.read_sql(query, engine)

,first_name,last_name,team_name,percent_home_games_won,num_home_games_won,num_home_games_played
0,Milo,Komenich,Packers,73.68,28,38
1,Ed,Stanczak,Packers,73.68,28,38
2,Murray,Mitchell,Packers,73.68,28,38
3,Rollie,Seltz,Packers,73.68,28,38
4,John,Hargis,Packers,73.68,28,38
...,...,...,...,...,...,...
3463,Matthew,Hickey,Steamrollers,35.44,28,79
3464,Bill,Downey,Steamrollers,35.44,28,79
3465,Tom,Callahan,Steamrollers,35.44,28,79
3466,Lee,Robbins,Steamrollers,35.44,28,79
3467,Andy,Tonkovich,Steamrollers,35.44,28,79

#### 5.2: Percent of home games won by all teams

In [22]:
query = text("""SELECT team_name, 
ROUND(AVG(CASE WHEN wl_home = 'W' THEN 1.0 ELSE 0.0 END)*100, 2) AS percent_home_games_won,
SUM(CASE WHEN wl_home = 'W' THEN 1 ELSE 0 END) AS num_home_games_won,
count(*) AS num_home_games_played
FROM 
	(select g.team_id_home, game_id, p.team_name, g.wl_home 
	from game g join player_info p ON p.team_id = g.team_id_home)
GROUP BY team_name
ORDER BY percent_home_games_won DESC
;""")

pd.read_sql(query, engine)

,team_name,percent_home_games_won,num_home_games_won,num_home_games_played
0,Capitols,71.81,1605,2235
1,Spurs,70.98,125976,177480
2,Olympians,70.95,1995,2812
3,Lakers,70.82,360393,508886
4,Celtics,70.42,349800,496716
5,Stags,69.84,1760,2520
6,Jazz,68.41,129438,189222
7,Trail Blazers,66.29,142200,214500
8,Suns,65.69,173160,263601
9,SuperSonics,64.57,118400,183360
10,Thunder,64.57,42920,66468
11,Blackhawks,64.47,16443,25506
12,Hawks,64.46,305330,473694
13,Bombers,64.00,1360,2125
14,Nuggets,63.85,123543,193482
15,Nationals,63.52,61413,96690
16,76ers,63.52,223320,351600
17,Bucks,63.25,129675,205023
18,Bulls,62.39,144300,231300
19,Rockets,62.24,150255,241395
20,Pacers,62.18,102850,165410
21,Warriors,62.06,359328,578983
22,Pistons,61.60,305128,495360
23,Heat,61.42,54093,88065
24,Knicks,60.23,312051,518079
25,Kings,59.81,181764,303912
26,Royals,59.81,100980,168840
27,Cavaliers,59.32,132392,223184
28,Mavericks,59.19,86800,146640
29,Rebels,58.06,162,279
30,Magic,58.02,46368,79912
31,Packers,57.31,5620,9806
32,Wizards,56.99,65760,115392
33,Zephyrs,56.99,8220,14424
34,Bullets,56.90,97122,170700
35,Raptors,56.87,31050,54602
36,Redskins,56.25,216,384
37,Pelicans,56.09,12200,21750
38,Hornets,53.46,37941,70965
39,Nets,53.20,94116,176916
40,Bobcats,53.01,9982,18830
41,Grizzlies,52.86,36580,69207
42,Braves,52.20,18581,35598
43,Clippers,52.20,107114,205212
44,Huskies,50.00,135,270
45,Timberwolves,49.06,40920,83400
46,Jets,48.28,154,319
47,Falcons,40.00,120,300
48,Ironmen,36.67,154,420
49,Steamrollers,35.44,588,1659

#### 6: Count of players in each height group (in inches) that were undrafted

In [15]:
query = text("""select count(*) AS num_players, height, substring(height FROM '^([0-9]+)')::INT * 12 + substring(height FROM '([0-9]+)$')::INT AS height_inches 
from player_info 
WHERE draft_round LIKE 'Undrafted' 
GROUP BY height, height_inches 
ORDER BY height_inches
;""")

pd.read_sql(query, engine)

    num_players height  height_inches
0             1    5-5           65.0
1             1    5-6           66.0
2             2    5-7           67.0
3             2    5-8           68.0
4             7    5-9           69.0
5            25   5-10           70.0
6            35   5-11           71.0
7            47    6-0           72.0
8            58    6-1           73.0
9            91    6-2           74.0
10           96    6-3           75.0
11           98    6-4           76.0
12          109    6-5           77.0
13           92    6-6           78.0
14           80    6-7           79.0
15           72    6-8           80.0
16           81    6-9           81.0
17           67   6-10           82.0
18           34   6-11           83.0
19           16    7-0           84.0
20           11    7-1           85.0
21            7    7-2           86.0
22            1    7-3           87.0
23            1    7-4           88.0
24            1    7-5           89.0
25            1    7-6           90.0
26           45   None            NaN

#### 7: Sort the head coaches by their ratio of home playoffs wins

In [32]:
query = text("""SELECT team_name_home, headcoach, percent_playoffs_games_won, num_playoffs_games_won, num_playoffs_games_played
FROM team_details t 
JOIN (
	SELECT g.team_name_home, g.team_id_home,
	ROUND(AVG(CASE WHEN wl_home = 'W' THEN 1.0 ELSE 0.0 END)*100, 2) AS percent_playoffs_games_won,
	SUM(CASE WHEN wl_home = 'W' THEN 1 ELSE 0 END) AS num_playoffs_games_won,
	count(*) AS num_playoffs_games_played
	FROM game g 
	WHERE season_type LIKE 'Playoffs'
	GROUP BY g.team_name_home, g.team_id_home
)
g ON g.team_id_home = t.team_id 
ORDER BY percent_playoffs_games_won DESC
;""")

pd.read_sql(query, engine)

,team_name_home,headcoach,percent_playoffs_games_won,num_playoffs_games_won,num_playoffs_games_played
0,Tri-Cities Blackhawks,Quin Snyder,100.00,1,1
1,Minneapolis Lakers,Darvin Ham,79.17,38,48
2,Syracuse Nationals,Nick Nurse,78.38,29,37
3,St. Louis Hawks,Quin Snyder,76.32,29,38
4,Los Angeles Lakers,Darvin Ham,73.75,222,301
5,Golden State Warriors,Steve Kerr,73.64,95,129
6,Philadelphia Warriors,Steve Kerr,72.73,24,33
7,San Antonio Spurs,Gregg Popovich,68.89,124,180
8,Rochester Royals,Mike Brown,68.42,13,19
9,Oklahoma City Thunder,Mark Daigneault,68.42,39,57
10,Detroit Pistons,Monty Williams,67.86,95,140
11,Miami Heat,Erik Spoelstra,67.19,86,128
12,Seattle SuperSonics,Mark Daigneault,67.02,63,94
13,Capital Bullets,Wes Unseld,66.67,2,3
14,San Francisco Warriors,Steve Kerr,66.67,14,21
15,Kansas City-Omaha Kings,Mike Brown,66.67,2,3
16,Chicago Bulls,Billy Donovan,66.24,104,157
17,Utah Jazz,Will Hardy,64.23,79,123
18,Portland Trail Blazers,Chauncey Billups,63.11,77,122
19,Philadelphia 76ers,Nick Nurse,63.07,111,176
20,Phoenix Suns,Frank Vogel,62.14,87,140
21,Houston Rockets,Ime Udoka,61.97,88,142
22,Washington Bullets,Wes Unseld,61.54,32,52
23,Charlotte Hornets,Steve Clifford,61.11,11,18
24,Milwaukee Bucks,Adrian Griffin,60.40,90,149
25,Buffalo Braves,Tyronn Lue,60.00,6,10
26,Sacramento Kings,Mike Brown,60.00,15,25
27,Indiana Pacers,Rick Carlisle,60.00,54,90
28,Ft. Wayne Zollner Pistons,Monty Williams,60.00,12,20
29,Dallas Mavericks,Jason Kidd,59.14,55,93
30,Denver Nuggets,Michael Malone,58.10,61,105
31,Toronto Raptors,None,55.93,33,59
32,Atlanta Hawks,Quin Snyder,55.56,65,117
33,Los Angeles Clippers,Tyronn Lue,55.56,15,27
34,Washington Wizards,Wes Unseld,54.84,17,31
35,Memphis Grizzlies,Taylor Jenkins,54.35,25,46
36,Baltimore Bullets,Wes Unseld,52.63,10,19
37,Minnesota Timberwolves,Chris Finch,51.85,14,27
38,Cincinnati Royals,Mike Brown,50.00,8,16
39,Brooklyn Nets,Jacque Vaughn,48.15,13,27
40,New Jersey Nets,Jacque Vaughn,47.37,18,38
41,Kansas City Kings,Mike Brown,45.45,5,11
42,LA Clippers,Tyronn Lue,37.93,11,29
43,Charlotte Bobcats,Steve Clifford,0.00,0,4

#### 8: Teams' average home/away points for quarters/games

In [21]:
query = text("""Select l1.team_city_name_home AS team_city_name, l1.team_nickname_home AS team_nickname, 
ROUND(AVG(l1.pts_qtr1_home)::NUMERIC, 2) AS avg_q1_home, ROUND(AVG(l1.pts_qtr2_home)::NUMERIC, 2) AS avg_q2_home, 
ROUND(AVG(l1.pts_qtr3_home)::NUMERIC, 2) AS avg_q3_home, ROUND(AVG(l1.pts_qtr4_home)::NUMERIC, 2) AS avg_q4_home, 
ROUND(AVG(l1.pts_qtr1_home + l1.pts_qtr2_home + l1.pts_qtr3_home + l1.pts_qtr4_home)::NUMERIC, 2) AS avg_home,
ROUND(AVG(l2.pts_qtr1_away)::NUMERIC, 2) AS avg_q1_away, ROUND(AVG(l2.pts_qtr2_away)::NUMERIC, 2) AS avg_q2_away, 
ROUND(AVG(l2.pts_qtr3_away)::NUMERIC, 2) AS avg_q3_away, ROUND(AVG(l2.pts_qtr4_away)::NUMERIC, 2) AS avg_q4_away,
ROUND(AVG(l1.pts_qtr1_away + l1.pts_qtr2_away + l1.pts_qtr3_away + l1.pts_qtr4_away)::NUMERIC, 2) AS avg_away
FROM line_score l1 join line_score l2 
ON l1.team_city_name_home = l2.team_city_name_away 
AND l1.team_nickname_home = l2.team_nickname_away 
GROUP BY l1.team_city_name_home, l1.team_nickname_home
;""")

pd.read_sql(query,engine)

,team_city_name,team_nickname,avg_q1_home,avg_q2_home,avg_q3_home,avg_q4_home,avg_home,avg_q1_away,avg_q2_away,avg_q3_away,avg_q4_away,avg_away
0,Adelaide,36ers,33.00,38.00,25.00,38.00,134.00,16.00,27.00,27.00,28.00,124.00
1,Anderson,Packers,30.50,25.50,10.50,14.50,81.00,19.00,24.50,17.50,21.00,81.00
2,Atlanta,Hawks,25.88,25.40,25.36,25.50,102.14,25.58,25.53,25.56,25.40,101.77
3,Baltimore,Bullets,24.70,24.83,25.36,26.51,101.14,24.67,25.17,25.77,26.48,101.28
4,Barcelona,Regal FC,23.00,29.00,24.50,24.00,100.50,19.00,25.00,24.00,36.00,101.00
...,...,...,...,...,...,...,...,...,...,...,...,...
84,Washington,Capitols,20.78,20.29,19.34,20.55,77.30,19.09,19.11,18.66,20.36,71.52
85,Washington,Wizards,25.57,25.08,24.89,24.65,100.19,25.74,25.14,24.98,24.76,102.10
86,Waterloo,Hawks,20.00,19.50,19.50,23.50,82.50,20.00,23.00,22.00,12.00,98.50
87,West NBA All Stars,West,31.40,32.33,32.16,31.74,127.63,29.89,31.46,30.13,31.74,128.70
88,Zalgiris Kaunas,Zalgiris Kaunas,19.50,25.50,28.50,24.00,97.50,16.00,23.00,17.00,32.00,110.00

#### 9: Teams' average points for quarters/games

In [28]:
query = text("""Select l1.team_city_name_home AS team_city_name, l1.team_nickname_home AS team_nickname, 
ROUND(AVG(l1.pts_qtr1_home + l2.pts_qtr1_away)::NUMERIC, 2) AS avg_q1,
ROUND(AVG(l1.pts_qtr2_home + l2.pts_qtr2_away)::NUMERIC, 2) AS avg_q2,
ROUND(AVG(l1.pts_qtr3_home + l2.pts_qtr3_away)::NUMERIC, 2) AS avg_q3,
ROUND(AVG(l1.pts_qtr4_home + l2.pts_qtr4_away)::NUMERIC, 2) AS avg_q4,
ROUND(AVG(l1.pts_qtr1_home + l2.pts_qtr1_away + l1.pts_qtr2_home + l2.pts_qtr2_away + l1.pts_qtr3_home + l2.pts_qtr3_away + l1.pts_qtr4_home + l2.pts_qtr4_away)::NUMERIC, 2) AS avg_game
FROM line_score l1 join line_score l2 
ON l1.team_city_name_home = l2.team_city_name_away 
AND l1.team_nickname_home = l2.team_nickname_away 
GROUP BY l1.team_city_name_home, l1.team_nickname_home
;""")

pd.read_sql(query,engine)

,team_city_name,team_nickname,avg_q1,avg_q2,avg_q3,avg_q4,avg_game
0,Adelaide,36ers,49.00,65.00,52.00,66.00,232.00
1,Anderson,Packers,49.50,50.00,28.00,35.50,163.00
2,Atlanta,Hawks,51.46,50.93,50.92,50.90,204.21
3,Baltimore,Bullets,49.37,50.00,51.13,52.99,203.01
4,Barcelona,Regal FC,42.00,54.00,48.50,60.00,204.50
...,...,...,...,...,...,...,...
84,Washington,Capitols,39.88,39.40,38.00,40.90,153.76
85,Washington,Wizards,51.31,50.22,49.87,49.41,200.81
86,Waterloo,Hawks,40.00,42.50,41.50,35.50,159.50
87,West NBA All Stars,West,61.28,63.78,62.29,63.48,250.84
88,Zalgiris Kaunas,Zalgiris Kaunas,35.50,48.50,45.50,56.00,185.50

#### 10: Sorted list of each player's number of years playing in the NBA

In [34]:
query = text("""SELECT first_name, last_name, to_year - from_year + 1 AS years_playing 
FROM player_info 
ORDER BY years_playing, last_name
;""")

pd.read_sql(query, engine)

     first_name     last_name  years_playing
0        Forest          Able            1.0
1        Donald      Ackerman            1.0
2       Charles         Acton            1.0
3          Deng          Adel            1.0
4          Josh       Akognon            1.0
...         ...           ...            ...
4166     Isaiah        Miller            NaN
4167       Nate  Pierre-Louis            NaN
4168    Daeqwon       Plowden            NaN
4169     Jaylen          Sims            NaN
4170        Pat       Spencer            NaN

[4171 rows x 3 columns]

#### 11: List all first round, first picks sorted by the year as well as home game win percentage

In [35]:
query = text("""SELECT first_name, last_name, draft_year,
ROUND(AVG(CASE WHEN wl_home = 'W' THEN 1.0 ELSE 0.0 END)*100, 2) AS percent_home_games_won,
SUM(CASE WHEN wl_home = 'W' THEN 1 ELSE 0 END) AS num_home_games_won,
count(*) AS num_home_games_played
FROM player_info p JOIN game g on p.team_id = g.team_id_home
WHERE draft_round='1' AND draft_number='1' 
GROUP BY first_name, last_name, draft_year
ORDER BY draft_year
;""")

pd.read_sql(query, engine)

,first_name,last_name,draft_year,percent_home_games_won,num_home_games_won,num_home_games_played
0,Andy,Tonkovich,1948,35.44,28,79
1,Howie,Shannon,1949,70.42,2200,3124
2,Charlie,Share,1950,64.47,1827,2834
3,Mark,Workman,1952,62.06,1824,2939
4,Ray,Felix,1953,60.23,1763,2927
5,Frank,Selvy,1954,70.82,2211,3122
6,Dick,Ricketts,1955,59.81,1683,2814
7,Si,Green,1956,56.99,1370,2404
8,Rod,Hundley,1957,70.82,2211,3122
9,Elgin,Baylor,1958,70.82,2211,3122
10,Bob,Boozer,1959,59.81,1683,2814
11,Oscar,Robertson,1960,59.81,1683,2814
12,Walt,Bellamy,1961,64.47,1827,2834
13,Bill,McGill,1962,60.23,1763,2927
14,Art,Heyman,1963,60.23,1763,2927
15,Jim,Barnes,1964,70.42,2200,3124
16,Fred,Hetzel,1965,62.06,1824,2939
17,Cazzie,Russell,1966,60.23,1763,2927
18,Jimmy,Walker,1967,61.60,1774,2880
19,Elvin,Hayes,1968,56.99,1370,2404
20,Kareem,Abdul-Jabbar,1969,70.82,2211,3122
21,Austin,Carr,1971,59.32,1273,2146
22,Larue,Martin,1972,66.29,1422,2145
23,Doug,Collins,1973,63.52,1861,2930
24,David,Thompson,1975,63.88,1247,1952
25,John,Lucas,1976,62.24,1431,2299
26,Kent,Benson,1977,61.60,1774,2880
27,Mychal,Thompson,1978,66.29,1422,2145
28,Magic,Johnson,1979,70.82,2211,3122
29,Mark,Aguirre,1981,59.19,1085,1833
30,James,Worthy,1982,70.82,2211,3122
31,Hakeem,Olajuwon,1984,62.24,1431,2299
32,Brad,Daugherty,1986,59.32,1273,2146
33,David,Robinson,1987,70.98,1448,2040
34,Larry,Johnson,1991,53.01,713,1345
35,Shaquille,O'Neal,1992,70.82,2211,3122
36,Glenn,Robinson,1994,63.25,1425,2253
37,Joe,Smith,1995,49.06,682,1390
38,Allen,Iverson,1996,63.52,1861,2930
39,Tim,Duncan,1997,70.98,1448,2040
40,Michael,Olowokandi,1998,52.20,1093,2094
41,Kwame,Brown,2001,56.99,1370,2404
42,Yao,Ming,2002,62.24,1431,2299
43,LeBron,James,2003,70.82,2211,3122
44,Dwight,Howard,2004,70.82,2211,3122
45,Andrew,Bogut,2005,63.25,1425,2253
46,Greg,Oden,2007,66.29,1422,2145
47,Blake,Griffin,2009,70.42,2200,3124
48,Kyrie,Irving,2011,59.19,1085,1833
49,Anthony,Davis,2012,70.82,2211,3122
50,Andrew,Wiggins,2014,62.06,1824,2939
51,Karl-Anthony,Towns,2015,49.06,682,1390
52,Ben,Simmons,2016,53.20,1023,1923
53,Markelle,Fultz,2017,58.02,828,1427
54,Deandre,Ayton,2018,65.69,1480,2253
55,Zion,Williamson,2019,56.09,488,870
56,Anthony,Edwards,2020,49.06,682,1390
57,Cade,Cunningham,2021,61.60,1774,2880
58,Paolo,Banchero,2022,58.02,828,1427

#### 12: Sort officials by the number of times officiating a playoffs game

In [33]:
query = text("""SELECT first_name, last_name, count(*) AS num_playoffs_officiated
FROM game g JOIN officials o ON g.game_id = o.game_id
WHERE season_type LIKE 'Playoffs'
GROUP BY official_id, first_name, last_name
ORDER BY num_playoffs_officiated DESC
;""")

pd.read_sql(query, engine)

   first_name   last_name  num_playoffs_officiated
0       Scott      Foster                      211
1        Marc       Davis                      175
2         Ken       Mauer                      162
3        Mike    Callahan                      162
4        Tony    Brothers                      160
..        ...         ...                      ...
85      Derek  Richardson                        1
86      Tommy       Nunez                        1
87        Ted   Bernhardt                        1
88      Terry      Durham                        1
89       Matt      Boland                        1

[90 rows x 3 columns]